services:
  mongodb :

    image : mongo:8.2.3

    container_name: mongodb

    ports : 
      - "27007:27017"

    volumes :
      - mongodata:/data/db
<<<<<<< HEAD

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

=======
    environment :
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
>>>>>>> 7187f73183e524281dc5ec5a762a962a71e75747
    networks :
      - backend
    
    restart: always

networks:
  backend: 

<<<<<<< HEAD
volumes:
  mongodata:



=======
volumes :
  mongodata:
>>>>>>> 7187f73183e524281dc5ec5a762a962a71e75747
 