version: '3.8'

services:
  mongodb :

    image : mongo:8.2.3

    container_name: mongodb

    ports : 
      - "27007:27017"

    volumes :
      - ./mongodb:/data/db

    networks :
      - backend
    
    restart: always

networks:
  backend: 
 